# Generated by Django 3.2.6 on 2022-03-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220318_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('E', 'Error'), ('N', 'Not Reviewed'), ('A', 'Accepted'), ('R', 'Reviewed')], default='R', max_length=1),
            preserve_default=False,
        ),
    ]
